version: '3'
services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    ports:
      - '443:443'
    restart : on-failure
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    ports:
      - '3306:3306'
    restart : on-failure

networks:
  default:
    external:
      name: network
  